### ISSUE TITLE
TLS Certificate is not trusted for cdn.islamic.network

### ISSUE THREAD

**Issue by ayob2k** [islamic-network/cdn.alquran.cloud#3]
@meezaan  Hello there, i'm just wondering if you are able to fix SSL for cnd.islamic.network pleaseee.
I'm trying to create an quran application and somehow java doesn't accept websites that arent trusted thankkk you and Allahh ijaaziikk !

![Capture](https://user-images.githubusercontent.com/77556307/129971121-3569e056-e6d1-47b3-9a0e-6db1f89e9817.PNG)
![image](https://user-images.githubusercontent.com/77556307/129971514-c033e9f5-86e2-4bd0-a814-bd77c5fac51e.png)

**Comment by meezaan** [comment]
@ayob2k The certificate is valid - the Intermediate Certificate you have may be the problem. Lets Encrypt changed the Intermediate CA, so the issuer is now R3, but it appears you may have the incorrect version or the version of Linux / Android you are using does not have the updated CA. See https://discord.com/channels/547154927248736266/547154927248736270/864210982859309136. You can get the correct CA at https://letsencrypt.org/certificates/. https://letsencrypt.org/certs/lets-encrypt-r3.pem to be specific.

**Comment by ayob2k** [comment]
@meezaan The certificate doesn't seem to be valid in my case. Please check the pictures below.
![image](https://user-images.githubusercontent.com/77556307/130318919-5ccbaec9-005c-42d8-b999-9fe8f5443ac2.png)

You can also try to verify the SSL certificate on https://www.digicert.com/help/
This is certificate for cdn.islamic.network :
![image](https://user-images.githubusercontent.com/77556307/130318990-3c6d7108-243f-42f7-bcfa-e14ef71987d9.png)



This is certificate for islamic.network
![image](https://user-images.githubusercontent.com/77556307/130318960-89480e01-9667-4989-b1d7-48e4d3ab0556.png)

**Comment by meezaan** [comment]
First things first, cdn.islamic.network and islamic.network are not related. 

islamic.network is hosted on GitHub - that certificate is a GitHub problem which I imagine will go away once they fix it.

Second, DigiCert is not an authority in saying their competitions certificates are correct - there are several instances that I have seen where they claim the certificate is not trusted, where in fact it is trusted by others and not them. Other people presented DigiCert as evidence of the certificate being invalid, but after updating intermediate certificates, their problems went away. There's a reason why this issue has occurred, and let's hope ACME issued certificates don't have a similar decision again.

Now, cdn.islamic.network is valid, and if it wasn't, a simple curl would fail, when it does not:

```
➜  ~ curl -I https://cdn.islamic.network/quran/audio/128/ar.alafasy/3.mp3
HTTP/2 200
server: nginx/1.14.2
date: Sat, 21 Aug 2021 11:41:22 GMT
content-type: audio/mpeg
content-length: 74523
last-modified: Sun, 18 Apr 2021 09:16:07 GMT
x-rgw-object-type: Normal
etag: "745b32efae58b737fa22957dd6770126"
x-amz-meta-s3cmd-attrs: atime:1601006971/ctime:1618493079/gid:20/gname:staff/md5:745b32efae58b737fa22957dd6770126/mode:33188/mtime:1601006971/uid:501/uname:meezaan
x-amz-storage-class: STANDARD
x-amz-request-id: tx000000000000001c50b0d-0060e921ac-33713bc-default
x-proxy-cache: HIT
x-cdn-server: sg.cdn.islamic.network
x-cdn-provider: Islamic Network
accept-ranges: bytes
```

Also, I have status cake monitoring all the certificates, and even there the certificate is valid.

There are also millions of requests processed over https each day, so the certificate is valid.

If you provide me the IP address you see when you ping the domain or the x-cdn-server header from a curl, I can check that particular edge node and see if it perhaps has an incorrect copy of the server.

**Comment by meezaan** [comment]
Also see https://www.sslshopper.com/ssl-checker.html#hostname=cdn.islamic.network - it also mentions that you might need to install an intermediate certificate but, but the actual certificate itself is valid.

**Comment by ayob2k** [comment]
Everything works just fine on "curl" but once I try to get that by using some plugins provided by java I get this certificate isn't trusted error.  
I really don't know if it is from the plugin provided by java or it's the domain itself, I will try some other mp3 files and check if they work properly.
If they do and the error still remains in my case, I will download the whole Quran API on my server and use it as it is with my domain.
Thanks a lot man, Allah bless you!

**Comment by meezaan** [comment]
@ayob2k you are having trouble with the api too, or just the cdn.

You can pass the ca to the java library when making the http call too. Are you using okhttp?

**Comment by ayob2k** [comment]
@meezaan i'm having problem with CDN only, only the mp3 files

**Comment by meezaan** [comment]
It's effectively the same certificate issued by the same authority, just for a different domain. If the library you are using to talk to the 2 is different, it's just a matter of passing it the correct intermediate CA.

**Comment by meezaan** [comment]
I've found the solution, I think - https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain. Give me a few hours, I'll reissue all the certificates.

**Comment by meezaan** [comment]
@ayob2k certificate updated with the ca bundled in. See https://www.sslshopper.com/ssl-checker.html#hostname=cdn.islamic.network. I will now add it to the other edge nodes too.

**Comment by meezaan** [comment]
@ayob2k All done. DigiCert is also happy now with the certificate.

Thanks for your persistence, I would have not looked at the alternate certificate chains from LetsEncrypt unless you had persisted.

God bless you!

**Comment by ayob2k** [comment]
@meezaan It's working fantastic now !!

Thank you so much man

**Comment by meezaan** [comment]
Alhamdulillah!
